name: Run Tests and Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Clean
        run: npm run clean
        working-directory: Express

      - name: Install Dependencies
        run: npm ci
        working-directory: Express

      - name: Build
        run: npm run build
        working-directory: Express

      - name: Test
        run: npm run testGithub
        working-directory: Express

      - name: Build Docker image
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          docker build -t lostfound-express-server \
            --build-arg JWT_SECRET=$JWT_SECRET \
            --build-arg DB_PASSWORD=$DB_PASSWORD \
              -t juda0/lostfounddockerhub:latest ./Express
        
      - name: Log in to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker info
            

      - name: Push Docker image
        run: docker juda0/lostfounddockerhub:latest

      # - uses: mr-smithers-excellent/docker-build-push@v6
      #   name: Build & push Docker image
      #   with:
      #     image: juda0/lostfounddockerhub
      #     tags: v1, latest
      #     registry: docker.io
      #     dockerfile: Express/Dockerfile
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}


            