# This workflow will install Node.js dependencies, clean, build, and test your project on every push
name: Run Tests

# Trigger the workflow on every push
on: push

# Set up the job
jobs:
  build:

    # Run the job on ubuntu-latest
    runs-on: ubuntu-latest

    # Set up the Node.js environment
    strategy:
      matrix:
        node-version: [16.x]

    # Steps to run the workflow
    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Clean the project, install Node.js dependencies, build, and test
      - name: Clean, Install Dependencies, Build, and Test
        run: |
          npm run clean
          npm ci
          npm run build
          npm test
        working-directory: Express
