name: Run Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Clean
        run: npm run clean
        working-directory: Express

      - name: Install Dependencies
        run: npm ci
        working-directory: Express

      - name: Build
        run: npm run build
        working-directory: Express

      - name: Test
        run: npm run testGithub
        working-directory: Express
